/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:f625d0f7-0f9e-48bd-806d-7d7f5b7fe8d4",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Aw9oI9rkJ",
    "aws_user_pools_web_client_id": "1d7iul1f3eqfnje85vl7o2lo92",
    "oauth": {}
};


export default awsmobile;
